import {
  haji_khusus,
  haji_furoda_sakinah,
  haji_furoda_warohmah,
} from "../../public/images/haji/haji";
import {
  paket_umroh_qonaah_juli_10,
  paket_umroh_qonaah_juli_5,
  paket_umroh_qonaah_juli_9,
  paket_umroh_qonaah_juli_22,
  paket_umroh_reguler_agustus_3,
  paket_umroh_qonaah_warahmah_agustus_14,
  paket_umroh_qonaah_warahmah_september_13,
  paket_umroh_qonaah_warahmah_oktober_16,
  paket_umroh_munko_november_5,
  paket_umroh_munko_november_5_12,
  paket_umroh_munko_november_5_sakinah,
  paket_umroh_munko_november_5_12_sakinah,
  paket_umroh_qonaah_desember_4,
  paket_umroh_qonaah_desember_14,
  paket_umroh_qonaah_desember_20,
  paket_umroh_qonaah_juli_26,
  paket_umroh_plus_thoif_sakinah_juli_21,
  paket_umroh_plus_thoif_sakinah_juli_31,
  paket_umroh_plus_thoif_agustus_21,
  paket_umroh_plus_thoif_agustus_30,
  paket_umroh_plus_turki_sakinah,
  paket_umroh_spesial_kemerdekaan_agustus_11,
  paket_umroh_plus_kemerdekaan_agustus,
  paket_umroh_spesial_maulid_september_3,
  paket_umroh_spesial_maulid_september_3_12,
  paket_umroh_plus_cairo_september_20,
  paket_umroh_plus_thoif_september_29,
  paket_umroh_plus_turki_oktober_5,
  paket_umroh_plus_thoif_oktober_12,
  paket_umroh_plus_thoif_oktober_26,
  paket_umroh_plus_thoif_november_30,
  paket_umroh_plus_thoif_desember_24,
  paket_umroh_plus_thoif_desember_24_12,
  paket_umroh_plus_thoif_desember_24_qonaah,
  paket_umroh_plus_thoif_desember_27,
  paket_umroh_plus_thoif_desember_27_12,
  paket_umroh_akhir_tahun,
} from "../../public/images/umrah/umrah";

// Dummy data untuk paket Haji dan Umrah
export const paketHajiUmrah = [
  {
    id: 1,
    namaPaket: "Paket Umroh Unggulan",
    deskripsi:
      "Raih momen spiritual terbaik  dari Al Bahjah Tour & Travel. Fasilitas terbaik untuk ibadah yang lebih barokah.",
    harga: {
      idr: 26500000,
      usd: null,
    },
    durasi: "9 Hari",
    destinasi: ["Makkah", "Madinah"],
    gambar: "/images/umrah/paket_umroh_qonaah_qonaah_juli_5.jpg",
    lokasi: "Arab Saudi",
    subPaket: [
      {
        id: 101,
        namaSubPaket: "Paket Qonaah (5 Juli 2025)",
        slug: "paket-qonaah-5-juli-2025",
        deskripsi:
          "Nikmati perjalanan umrah dengan harga terjangkau, fasilitas lengkap, dan bimbingan langsung dari Buya Yahya. Rasakan pengalaman ibadah yang lebih mendalam.",
        harga: {
          idr: 26500000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_juli_5],
        durasi: "P9D",
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-07-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 102,
        namaSubPaket: "Paket Qonaah (9 Juli 2025)",
        slug: "paket-qonaah-9-juli-2025",
        deskripsi:
          "Nikmati perjalanan umrah dengan harga terjangkau, fasilitas lengkap, dan bimbingan langsung dari Buya Yahya. Rasakan pengalaman ibadah yang lebih mendalam.",
        harga: {
          idr: 31000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_juli_9],
        durasi: "P12D",
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Qatar Airways",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-07-09",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 103,
        namaSubPaket: "Paket Qonaah (10 Juli 2025)",
        slug: "paket-qonaah-10-juli-2025",
        deskripsi:
          "Paket umrah dengan kenyamanan ekstra dan durasi yang lebih panjang. Cocok bagi Anda yang ingin menikmati setiap momen ibadah dengan lebih tenang dan khusyuk.",
        harga: {
          idr: 31000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_juli_10],
        durasi: "P12D",
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-07-10",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 104,
        namaSubPaket: "Paket Qonaah (22 Juli 2025)",
        slug: "paket-qonaah-22-juli-2025",
        deskripsi:
          "Paket umrah dengan kenyamanan ekstra dan durasi yang lebih panjang. Cocok bagi Anda yang ingin menikmati setiap momen ibadah dengan lebih tenang dan khusyuk.",
        harga: {
          idr: 26500000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_juli_22],
        durasi: "P9D",
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Qatar Airways",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-07-22",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 105,
        namaSubPaket: "Paket Qonaah (26 Juli 2025)",
        slug: "paket-qonaah-26-juli-2025",
        deskripsi:
          "Perjalanan umrah dengan pelayanan premium dan akomodasi terbaik. Ideal bagi Anda yang ingin merasakan ibadah dengan lebih nyaman dan berkesan.",
        harga: {
          idr: 31500000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_juli_26],
        durasi: "P9D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-07-26",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 106,
        namaSubPaket: "Paket Reguler (03 Agustus 2025)",
        slug: "paket-reguler-03-agustus",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 34000000,
          usd: null,
        },
        gambar: [paket_umroh_reguler_agustus_3],
        durasi: "P12D",
        hotel_makkah: "Maysan Al-Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-08-03",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 107,
        namaSubPaket: "Paket Qonaah (04 Agustus 2025)",
        slug: "paket-qonaah-04-agustus",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 39000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_warahmah_agustus_14],
        durasi: "P12D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-08-04",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 108,
        namaSubPaket: "Paket Qonaah (09 September 2025)",
        slug: "paket-qonaah-09-september",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 27000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_warahmah_september_13],
        durasi: "P9D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-09-09",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 109,
        namaSubPaket: "Paket Qonaah (16 Oktober 2025)",
        slug: "paket-qonaah-16-oktober",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 31000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_warahmah_oktober_16],
        durasi: "P12D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-10-31",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1010,
        namaSubPaket: "Paket Munajat Kubro (5 November 2025)",
        slug: "paket-munko-5-november",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 29500000,
          usd: null,
        },
        gambar: [paket_umroh_munko_november_5],
        durasi: "P9D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-11-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1011,
        namaSubPaket: "Paket Munajat Kubro (5 November 2025)",
        slug: "paket-munko-5-november-12-hari",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 32000000,
          usd: null,
        },
        gambar: [paket_umroh_munko_november_5_12],
        durasi: "P12D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-11-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1012,
        namaSubPaket: "Paket Munajat Kubro - Sakinah (5 November 2025)",
        slug: "paket-munko-5-november-9-hari-sakinah",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 32000000,
          usd: null,
        },
        gambar: [paket_umroh_munko_november_5_sakinah],
        durasi: "P9D",
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-11-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1013,
        namaSubPaket: "Paket Munajat Kubro - Sakinah (5 November 2025)",
        slug: "paket-munko-5-november-12-hari-sakinah",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 34500000,
          usd: null,
        },
        gambar: [paket_umroh_munko_november_5_12_sakinah],
        durasi: "P12D",
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-11-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1014,
        namaSubPaket: "Paket Munajat Kubro (4 Desember 2025)",
        slug: "paket-munko-4-desember",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 32000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_desember_4],
        durasi: "P12D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-12-04",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1015,
        namaSubPaket: "Paket Munajat Kubro (14 Desember 2025)",
        slug: "paket-munko-14-desember",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 29500000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_desember_14],
        durasi: "P9D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-12-14",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 1016,
        namaSubPaket: "Paket Munajat Kubro (20 Desember 2025)",
        slug: "paket-munko-20-desember",
        deskripsi:
          "Paket umrah eksklusif dengan layanan kelas atas, akomodasi terbaik, dan perjalanan ibadah yang lebih nyaman serta berkesan.",
        harga: {
          idr: 32000000,
          usd: null,
        },
        gambar: [paket_umroh_qonaah_desember_20],
        durasi: "P12D",
        hotel_makkah: "Makarim Ajyad / Setaraf",
        hotel_madinah: "Front Taiba / Setaraf",
        penerbangan: "Emirates / Etihad",
        keberangkatan_hijriah: "1446 H",
        keberangkatan_masehi: "2025-12-20",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
    ],
  },

  {
    id: 2,
    namaPaket: "Paket Umroh Spesial",
    deskripsi:
      "Paket umroh spesial dengan berbagai fasilitas yang disesuaikan dengan kebutuhan perjalanan spiritual Anda",
    harga: {
      idr: 33000000,
      usd: null,
    },
    durasi: "9 - 12 Hari",
    destinasi: ["Makkah", "Madinah"],
    gambar: "/images/umrah/paket_umroh_plus_thoif_sakinah_juli_31.jpg",
    lokasi: "Arab Saudi",
    subPaket: [
      {
        id: 201,
        namaSubPaket: "Umroh Plus Turki (19 Juli 2025)",
        slug: "umroh-plus-turki-sakinah", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Turki dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 37000000,
          usd: null,
        },
        durasi: "P13D",
        gambar: [paket_umroh_plus_turki_sakinah],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-07-19",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 202,
        namaSubPaket: "Umroh Plus Thoif (21 Juli 2025)",
        slug: "umroh-plus-thoif-21-juli-2025", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 31500000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_sakinah_juli_21],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-07-21",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 203,
        namaSubPaket: "Umroh Plus Thoif (31 Juli 2025)",
        slug: "umroh-plus-thoif-31-juli-2025", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 33000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_plus_thoif_sakinah_juli_31],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-07-31",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 204,
        namaSubPaket: "Umroh Plus Thoif (21 Agustus 2025)",
        slug: "umroh-plus-thoif-21-agustus-2025", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 33000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_plus_thoif_agustus_21],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-08-21",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 205,
        namaSubPaket: "Umroh Plus Thoif (30 Agustus 2025)",
        slug: "umroh-plus-thoif-30-agustus-2025", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 32000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_plus_thoif_agustus_30],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-08-21",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 206,
        namaSubPaket: "Umroh  Kemerdekaan (11 agustus 2025)",
        slug: "umroh-spesial-kemerdekaan-11-agustus", // Slug ditambahkan
        deskripsi:
          "Umroh Spesial Kemerdekaan dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 26500000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_spesial_kemerdekaan_agustus_11],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-08-11",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 207,
        namaSubPaket: "Umroh  Kemerdekaan (14 agustus 2025)",
        slug: "umroh-spesial-kemerdekaan", // Slug ditambahkan
        deskripsi:
          "Umroh Spesial Kemerdekaan dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 26500000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_kemerdekaan_agustus],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-08-14",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 208,
        namaSubPaket: "Umroh Spesial Maulid (03 September 2025)",
        slug: "umroh-spesial-maulid", // Slug ditambahkan
        deskripsi:
          "Umroh Spesial Maulid dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 34000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_spesial_maulid_september_3],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-09-03",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 209,
        namaSubPaket: "Umroh Spesial Maulid (03 September 2025)",
        slug: "umroh-spesial-maulid-9-hari", // Slug ditambahkan
        deskripsi:
          "Umroh Spesial Maulid dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 32000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_spesial_maulid_september_3_12],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-09-03",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2010,
        namaSubPaket: "Umroh Plus Cairo (20 September 2025)",
        slug: "umroh-plus-cairo-20-september", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Cairo dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 35000000,
          usd: null,
        },
        durasi: "P13D",
        gambar: [paket_umroh_plus_cairo_september_20],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-09-20",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2011,
        namaSubPaket: "Umroh Plus Thoif (29 September 2025)",
        slug: "umroh-plus-thoif-29-september", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 31000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_september_29],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-09-29",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2012,
        namaSubPaket: "Umroh Plus Turki (05 Oktober 2025)",
        slug: "umroh-plus-turki-05-oktober", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Turki dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 37000000,
          usd: null,
        },
        durasi: "P13D",
        gambar: [paket_umroh_plus_turki_oktober_5],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Turkish Airlines",
        keberangkatan_masehi: "2025-10-05",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2013,
        namaSubPaket: "Umroh Plus Thoif (12 Oktober 2025)",
        slug: "umroh-plus-thoif-12-oktober", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 31000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_oktober_12],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-10-12",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2014,
        namaSubPaket: "Umroh Plus Thoif (26 Oktober 2025)",
        slug: "umroh-plus-thoif-26-oktober", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 34000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_plus_thoif_oktober_26],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-10-26",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2015,
        namaSubPaket: "Umroh Plus Thoif (30 November 2025)",
        slug: "umroh-plus-thoif-30-november", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 32000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_november_30],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-11-30",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2016,
        namaSubPaket: "Umroh Plus Thoif (24 Desember 2025)",
        slug: "umroh-plus-thoif-24-desember", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 39500000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_desember_24],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-12-24",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2017,
        namaSubPaket: "Umroh Plus Thoif (24 Desember 2025)",
        slug: "umroh-plus-thoif-24-desember-12-hari", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 43000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_desember_24_12],
        hotel_makkah: "Maysan Al Maqam / Setaraf",
        hotel_madinah: "Al Ansar Golden Tulip / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-12-24",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2018,
        namaSubPaket: "Umroh Plus Thoif - Qonaah (24 Desember 2025)",
        slug: "umroh-plus-thoif-24-desember-qonaah", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 34000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_desember_24_qonaah],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Saudia Airlines",
        keberangkatan_masehi: "2025-12-24",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2019,
        namaSubPaket: "Umroh Plus Thoif (27 Desember 2025)",
        slug: "umroh-plus-thoif-27-desember-qonaah", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 32000000,
          usd: null,
        },
        durasi: "P9D",
        gambar: [paket_umroh_plus_thoif_desember_27],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Emirates Airlines / Etihad Airways",
        keberangkatan_masehi: "2025-12-27",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2020,
        namaSubPaket: "Umroh Plus Thoif (27 Desember 2025)",
        slug: "umroh-plus-thoif-27-desember-qonaah-12-hari", // Slug ditambahkan
        deskripsi:
          "Umroh Plus Thoif dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 34000000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_plus_thoif_desember_27_12],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Emirates Airlines / Etihad Airways",
        keberangkatan_masehi: "2025-12-27",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 2021,
        namaSubPaket: "Umroh Akhir Tahun (31 Desember 2025)",
        slug: "umroh-akhir-tahun", // Slug ditambahkan
        deskripsi:
          "Umroh Akhir Tahun dengan pengalaman spiritual dan wisata budaya lengkap..",
        harga: {
          idr: 34500000,
          usd: null,
        },
        durasi: "P12D",
        gambar: [paket_umroh_akhir_tahun],
        hotel_makkah: "Al Ayam Ajyad / Setaraf",
        hotel_madinah: "Abraj Taba / Setaraf",
        penerbangan: "Emirates Airlines / Etihad Airways",
        keberangkatan_masehi: "2025-12-31",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
    ],
  },

  {
    id: 3,
    namaPaket: "Paket Haji",
    deskripsi:
      "Perjalanan haji dengan pilihan paket yang sesuai dengan kebutuhan Anda, didampingi oleh Buya Yahya.",
    harga: {
      idr: 345000000,
      usd: 19500,
    },
    durasi: null,
    lokasi: "Arab Saudi",
    gambar: "/images/haji/haji_furoda_sakinah_2025.jpg",
    subPaket: [
      {
        id: 301,
        namaSubPaket: "Haji Furoda - Paket Sakinah",
        slug: "haji-furoda-paket-sakinah", // Slug ditambahkan
        deskripsi:
          "Paket haji non-kuota (Furoda) dengan fasilitas standar dan hotel yang nyaman.",
        harga: {
          idr: 320000000,
          usd: 19500,
        },
        gambar: [haji_furoda_sakinah],

        hotel_makkah: "Snood / Fajar Badea 2",
        hotel_madinah: "Jawharat Al-Raseed",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 302,
        namaSubPaket: "Haji Furoda - Warohmah",
        slug: "haji-furoda-paket-warohmah", // Slug ditambahkan
        deskripsi:
          "Paket haji non-kuota (Furoda) dengan fasilitas premium dan hotel berbintang.",
        harga: {
          idr: 390000000,
          usd: 27500,
        },
        gambar: [haji_furoda_warohmah],

        hotel_makkah: "Fair Mont / setaraf",
        hotel_madinah: "Dallah Taibah / Setaraf",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
      {
        id: 303,
        namaSubPaket: "Haji Khusus - 2025",
        slug: "haji-khusus", // Slug ditambahkan
        deskripsi:
          "Paket haji khusus bersama Buya Yahya, dengan akomodasi dan layanan VIP sepanjang ibadah haji.",
        harga: {
          idr: 275000000,
          usd: 11500,
        },
        gambar: [haji_khusus],

        hotel_makkah: "Fair Mont / setaraf",
        hotel_madinah: "Dallah Taibah / Setaraf",
        include: [
          "Visa",
          "Tiket PP",
          "Hotel",
          "Handling Makkah Madinah",
          "City Tour Makkah 1x",
          "City Tour Madinah 1x",
          "Makan 3x",
          "Manasik 1x",
          "Perlengkapan",
          "💧Zam zam 5 Lt",
          "🚌 Bus Makkah Madinah",
          "🎥 Dokumentasi",
          "⛑ Include Travel Insurance selama Perjalanan Umroh",
        ],
        perlengkapan: [
          "🧳 Koper Bagasi 22inc - Kabin 14inc",
          "🎒 Tas Pasport - tas sandal",
          "👘 Kain Batik, (2m)",
          "👳🏼 Kain Ihram + Sabuk",
          "🧕🏻 Jilbab Syar'i",
          "📗 Buku Panduan Doa",
          "🔖 ID Card",
          "🎀 Syal",
        ],
      },
    ],
  },
];
